apiVersion: v1 # 版本号 v1
kind: Service # pod
metadata: # 元数据
  name: String  # pod名称
  namespace: string # pod所属的命名空间，默认为default
  labels: # 自定义标签列表
    name: string
  annotations:  # 自定义注解列表
    name: string
spec: # pod中容器详细定义
  selector: []
  type: string
  clusterIP: string
  sessionAffinity: string
  ports:
  - name: string
    protocol: string
    port: int
    targetPort: int
    nodePort: int
  status:
    loadBalancer:
      ingress:
        ip: string
        hostname: string