apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
spec:
  scaleTargetRef:
    kind: ReplicationController
    name: php-apache
    apiVersion: v1
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 25